
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



# Starter pipeline
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureContainerRegistry: '{"loginServer":"regname0.azurecr.io", "id" : "/subscriptions/14f907f3-64fd-4da1-bf98-3ef778f57217/resourceGroups/rg_dev_inder/providers/Microsoft.ContainerRegistry/registries/Regname0"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:


